[project]
org-name = "ballerina"
version = "@toml.version@"

[dependencies]
"ballerina/auth" = "@stdlib.auth.version@"
"ballerina/crypto" = "@stdlib.crypto.version@"
"ballerina/log" = "@stdlib.log.version@"
"ballerina/config" = "@stdlib.config.version@"
"ballerina/time" = "@stdlib.time.version@"
"ballerina/system" = "@stdlib.system.version@"
"ballerina/cache" = "@stdlib.cache.version@"
"ballerina/stringutils" = "@stdlib.stringutils.version@"
"ballerina/io" = "@stdlib.io.version@"
"ballerina/task" = "@stdlib.task.version@"

[platform]
target = "java8"

    [[platform.libraries]]
    artifactId = "ldap"
    version = "@project.version@"
    path = "../ldap-native/build/libs/ldap-native-@project.version@.jar"
    groupId = "ballerina"
    modules = ["ldap"]
