[package]
org = "ballerina"
name = "auth"
version = "2.9.0"
authors = ["Ballerina"]
keywords = ["security", "authentication", "basic auth"]
repository = "https://github.com/ballerina-platform/module-ballerina-auth"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.8.0"

[platform.java11]
graalvmCompatible = true

[[platform.java11.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "auth-native"
version = "2.9.0"
path = "../native/build/libs/auth-native-2.9.0.jar"
