[package]
org = "ballerina"
name = "auth"
version = "@toml.version@"

[[dependency]]
org = "ballerina"
name = "cache"
version = "@stdlib.cache.version@"

[[dependency]]
org = "ballerina"
name = "config"
version = "@stdlib.config.version@"

[[dependency]]
org = "ballerina"
name = "crypto"
version = "@stdlib.crypto.version@"

[[dependency]]
org = "ballerina"
name = "log"
version = "@stdlib.log.version@"

[[dependency]]
org = "ballerina"
name = "regex"
version = "@stdlib.regex.version@"

[[platform.java11.dependency]]
path = "../auth-native/build/libs/auth-native-@project.version@.jar"
groupId = "ballerina"
artifactId = "auth"
version = "@project.version@"
